/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;
        
import java.awt.Color;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.lang.reflect.Array;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import org.apache.jena.query.Query;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.Literal;
import org.apache.jena.util.FileManager;
import org.apache.jena.iri.impl.Main;
import org.apache.jena.query.ResultSetFormatter;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.RDFNode;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.Statement;
import org.apache.jena.rdf.model.StmtIterator;
import org.apache.jena.rdfconnection.RDFConnection;
import org.apache.jena.rdfconnection.RDFConnectionFactory;
import static org.apache.jena.shacl.lib.G.subject;

/**
 *
 * @author Asususer
 */
public class NewJFrame extends javax.swing.JFrame {

    
    public static ArrayList<String> ListTabelsWithCol = new ArrayList<String>();//"Tabels" && "Tabel Column"
    public static ArrayList<String> ListTabels = new ArrayList<String>();//Tabels Name
    public static ArrayList<String> ListColumns = new ArrayList<String>();//As: "Tabel Column"  
    public static ArrayList<String> ListColsOfSpecificTabel = new ArrayList<String>();//Columns
    
    static Model model = null;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/arrow1.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("QUERYING ALL TRIPLES DATABASE");
        jButton1.setAutoscrolls(true);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 102));
        jButton3.setText("Take Tables");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Take Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "?Subject", "?Predicate", "?Object" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Columns:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.getAccessibleContext().setAccessibleName("QUERY ALL\n TRIPLES\n DATABASE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      jTextPane1.setText("");
        String g="";
        String qs="";
         String s="";
        if(jComboBox1.getSelectedItem().equals("ALL")){
             g="?Subject ?Predicate ?Object";
        }else
            g=(String) jComboBox1.getSelectedItem();
qs=
"prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>"+
"prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>"+
"prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>"+
        
  "SELECT * WHERE { ?Subject ?Predicate ?Object. "
     //   + "FILTER (?Predicate !=rdfs:label). "
       // + "FILTER (?Predicate !=rdf:type). "
        + "}"
        +"GROUP BY "+g;
       
        
      // (?a as ?Subject) (?z as ?Predicate) (?x as ?Object) 
        

Query query= null;
 query= QueryFactory.create(qs);
QueryExecution qExec = null;
 qExec = QueryExecutionFactory.create(query, model);

ResultSet rs = null;
rs = qExec.execSelect() ;

int i=0;
while(rs.hasNext()){
        
        ByteArrayOutputStream go = new ByteArrayOutputStream ();
        ResultSetFormatter.out((OutputStream)go ,rs, query);
        s = go.toString();
        
                  //return the search results (String);)
        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground,Color.red);
        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        
        int len = jTextPane1.getDocument().getLength();
        jTextPane1.setCaretPosition(len);
        jTextPane1.setCharacterAttributes(aset, false);
        jTextPane1.replaceSelection(s);
        
                                   
    try {
        s = new String(go.toByteArray(), "UTF-8");
    } catch (UnsupportedEncodingException ex) {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
                    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    
 
        takeData();
        
        

       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        takeTabels();
        putTabels();
        
      
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox2.getSelectedItem()!=null){     
        jComboBox3.removeAllItems();
       takeAllColumns();
        takeColumns();
        
        for (int i = 0; i < ListColsOfSpecificTabel.size(); i++) {
                       // jTextArea1.setFont(new java.awt.Font("Lucida Console", 0, 10));
                      jComboBox3.addItem(ListColsOfSpecificTabel.get(i));  
           
                      }
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged
public void takeTabels(){
ListTabelsWithCol.clear();
ListTabels.clear();
String qs=
"prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>"+
"prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>"+
"prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>"+
        
  "SELECT DISTINCT ?Object WHERE { ?Subject rdfs:label ?Object. "
     
        + "}";        

Query query= QueryFactory.create(qs);
QueryExecution qExec = QueryExecutionFactory.create(query, model);


ResultSet rs = qExec.execSelect() ;

    while(rs.hasNext()){
    QuerySolution qsol=rs.nextSolution();
    String tabelName= qsol.getLiteral("Object").getString();
    int i=0;
    if(tabelName.contains("#") ){
    i=tabelName.indexOf("#");
    tabelName=tabelName.substring(0,i-1);
    ListTabels.add(tabelName);
    
    }else{
     ListTabelsWithCol.add(tabelName);
    
    }
    //delete repeated tables
   Set<String> set=new HashSet<>(ListTabels);
        ListTabels.clear();
        ListTabels.addAll(set);
    }
    
       /* ByteArrayOutputStream go = new ByteArrayOutputStream ();
        ResultSetFormatter.out((OutputStream)go ,rs, query);
        String s = go.toString();*/
        
                  //return the search results (String);)
        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground,Color.red);
        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        String q=
                    "\nprefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"+
                    "prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"+
                    "prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>\n\n"+
                    "SELECT DISTINCT ?Object WHERE { ?Subject rdfs:label ?Object."+"}\n"+
                    "\n-------------------------------------------------------------------";
       
        int len = jTextPane1.getDocument().getLength();
        jTextPane1.setCaretPosition(len);
        jTextPane1.setCharacterAttributes(aset, false);
        jTextPane1.replaceSelection(q);
        
    
                  
                  
    /*try {
        s = new String(go.toByteArray(), "UTF-8");
    } catch (UnsupportedEncodingException ex) {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }*/
       
        
//        List<String> unicListTables=ListTabels.stream().distinct().collect(Collectors.toList());
        

}

public void putTabels(){
           jComboBox2.removeAllItems(); //  combobox tabels
                      for (int i = 0; i < ListTabels.size(); i++) {
                       // jTextArea1.setFont(new java.awt.Font("Lucida Console", 0, 10));
                      jComboBox2.addItem(ListTabels.get(i));  
           
                      }
                      
                      StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground,Color.black);
        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        String q="";  
        q="\n----------------------------------------The Tabels--------------------------------------\n\n";
         for (int i = 0; i < ListTabels.size(); i++) {
                          
                         q=q+  ListTabels.get(i)+" * ";
                          
                          }
                      
                      
         q=q+"\n\n----------------------------------------------------------------------------------------";
       
        int len = jTextPane1.getDocument().getLength();
        jTextPane1.setCaretPosition(len);
        jTextPane1.setCharacterAttributes(aset, false);
        jTextPane1.replaceSelection(q);
        
                         
}

public void takeAllColumns(){
 ListColumns.clear();
    int a=0;
        for(int i=0;i<ListTabelsWithCol.size();i++){
            
             for(int j=0;j<ListTabels.size();j++){
             if(ListTabelsWithCol.get(i).matches(ListTabels.get(j))){
             a=1;
             break;
        }
              
        
             }
             
             if(a==0)
                 ListColumns.add(ListTabelsWithCol.get(i));
             a=0;
        }
 

}

public void takeColumns(){
 
String p="",k="",s="";
int d=0;
ListColsOfSpecificTabel.clear();
  for (int i = 0; i < ListColumns.size(); i++) {   
             if(ListColumns.get(i).startsWith((String) jComboBox2.getSelectedItem())){
              k=ListColumns.get(i);
              d=k.indexOf(" ");
              p=k.substring(d);//(k.replace(" ", "_")).toString();
             ListColsOfSpecificTabel.add(p);
             }
  }
  

}
      public void takeData(){
          jTextPane1.setText("");
          String p="",s="";
             s="vocab:"+jComboBox2.getSelectedItem()+jComboBox3.getSelectedItem();
             p=(s.replace(" ", "_")).toString();

              
String qs=
"prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>"+
"prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>"+
"prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>"+     
  "SELECT ?Object WHERE { ?Subject "+p+" ?Object. "
     
        + "}";        

Query query= QueryFactory.create(qs);
QueryExecution qExec = QueryExecutionFactory.create(query, model);


ResultSet rs = qExec.execSelect() ;
 StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground,Color.blue);
        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        String q=
                    "\nprefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"+
                    "prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"+
                    "prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>\n\n"+
                    "SELECT DISTINCT ?Object WHERE { ?Subject "+p+" ?Object."+"}\n"+
                    "-------------------------------------------------------------------------------------------------------------------\n\n";
        
        q=q+"\n****-----------------------------------( The Column:"+jComboBox3.getSelectedItem()+" )----------------------------------****\n\n";                                
         q=q+"****----------------------------------------( Of Table: "+jComboBox2.getSelectedItem()+" )---------------------------------------****\n\n";
       
        int len = jTextPane1.getDocument().getLength();
        jTextPane1.setCaretPosition(len);
        jTextPane1.setCharacterAttributes(aset, false);
        jTextPane1.replaceSelection(q);
while(rs.hasNext()){
    QuerySolution qsol=rs.nextSolution();
    String name= qsol.getLiteral("Object").getString();
      jTextPane1.replaceSelection(name+"\n"+"---------"+"\n");
   
}
       
    
 

}


    /**
     * @param args the command line arguments
     */
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
    
FileManager.get().addLocatorClassLoader(Main.class.getClassLoader());

try
{
model= FileManager.get().loadModel("C:/d2rq-0.8.1/mimiciiiv14.rdf");

String qs=
"prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>"+
"prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>"+
"prefix foaf: <http://xmlns.com/foaf/0.1/>"+
"prefix vocab: <file:///C:/d2rq-0.8.1/vocab/>"+
//"SELECT * WHERE { ?a vocab:producttable_prodName ?x. }";
//"SELECT * WHERE { ?a vocab:usertable_userName ?x. }";
//"SELECT * WHERE { ?a vocab:producttable_initPrice ?x. }";  
//"SELECT * WHERE { ?a vocab:producttable_isSold ?x. }";  
//"SELECT * WHERE { ?a vocab:producttable_prodId ?x. }";        
//"SELECT * WHERE { ?a vocab:bidoffertable_offerPrice ?x. }";
  "SELECT * WHERE { ?a ?z ?x. "
        + "FILTER (?z !=rdfs:label) ."
        + "FILTER (?z !=rdf:type) ."
        + "}"
        +"GROUP BY ?x";

      
        

Query query= QueryFactory.create(qs);
QueryExecution qExec = QueryExecutionFactory.create(query, model);


try {
ResultSet rs = qExec.execSelect() ;

int i=0;
while(rs.hasNext()){
QuerySolution qsol=rs.nextSolution();

 // Literal name=qsol.getLiteral("a");System.out.println(name);
//Resource rname=qsol.getResource("z");System.out.println(rname);
/*String nomactiviter = qsol.getLiteral("x").getString();//System.out.println(nomactiviter.toString());
ListActivite.add(nomactiviter);*/

                 
      
        
                      /*      RDFNode x1 = qsol.get("x");
                            String xx = String.valueOf(x1);
                            ByteBuffer xxx = Charset.forName("UTF-8").encode(xx);
                            String xs = xxx.toString();
                            System.out.println(x1);*/

    
}//end while


}finally{
qExec.close();
}


}catch(Exception e)
{
System.out.println(e);
}


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

/*StmtIterator iter = model.listStatements();
while (iter.hasNext()) {
    Statement stmt      = iter.nextStatement();  // get next statement
    Resource  subject   = stmt.getSubject();     // get the subject
    Property  predicate = stmt.getPredicate();   // get the predicate
    RDFNode   object    = stmt.getObject();      // get the object

   /* System.out.print(subject.toString());
    System.out.print(" " + predicate.toString() + " ");
    if (object instanceof Resource) {
       System.out.print(object.toString());
    } else {
        // object is a literal
        System.out.print(" \"" + object.toString() + "\"");
    }

    System.out.println(" .");
}*/


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    public static javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
